<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- UseDevelopmentEmulator=true é suportado a partir da 7.18 -->
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.*" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.*" />
  </ItemGroup>

</Project>
